### ISSUE TITLE
(node:19792) electron: Failed to load URL: http://localhost:8889/ with error: ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by weir1** [ohmplatform/FreedomGPT#115]
Unable to connect or start app

**Comment by G-bit94** [comment]
Facing the same problem here using the default settings? @weir1 were you able to resolve the problem?

**Comment by bolens** [comment]
@G-bit94 not sure if you are still facing the issue but there is a "workaround" from their discord (#6 in the troubleshooting channel)

>〔6〕"Storage doesnt get detected or buttons are greyed out"
Solution: This solution will only work for the current version(1.1.3) and is pretty janky
1.Download the file from the following link(https://cdn.discordapp.com/attachments/559767094087122964/1113171053187960962/index.js)
2.Go to "C:\Users\<YOUR_USERNAME>\AppData\Local\FreedomGPT\app-1.1.3\resources\app.webpack\renderer\main_window" and put the file you just donwloaded in there by replacing the old one
3.FreedomGPT should "work" now

**Comment by G-bit94** [comment]
@bolens That worked and even seems to have also solved a problem I had with running a certain NextJS project. Thank you

**Comment by geezluise** [comment]
I am getting this same problem.  here is my error

Server listening on port 8888
(node:8394) electron: Failed to load URL: http://localhost:3001/ with error: ERR_CONNECTION_REFUSED
(Use `electron --trace-warnings ...` to show where the warning was created)
update-electron-app config looks good; aborting updates since app is in development mode
[8426:0423/042236.005243:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!

**Comment by alishefaee** [comment]
I recently faced this problem for a project while a few months ago it was working correctly.
```
    "electron": "^31.0.2",
    "electron-builder": "^24.13.3",
```
Running in preview mode ```npm run start``` everything works fine so the problem is with dev server.
