### ISSUE TITLE
Errors after starting the windows app

### ISSUE THREAD

**Issue by bsolyom** [ohmplatform/FreedomGPT#16]
I have started the servers and the application, and when I write a message, I get no reply, only these error messages

![error1](https://user-images.githubusercontent.com/63775925/230898591-7f0d8e66-e6a1-4447-9196-5291982c464e.png)
![error2](https://user-images.githubusercontent.com/63775925/230898598-c90c6737-7cea-465e-a971-3bb53c179317.png)

**Comment by testproghub** [comment]
This app uses ports 8889 and 9000, make sure these ports are available. If you restart your system you are good.

**Comment by coretravis** [comment]
@Konzol 
Had this same issue until I realized it was because I was missing the prod flag with the 'yarn start' command
Instead of 'yarn start:prod' i used just 'yarn start'

**Comment by Nguyenpham89** [comment]
Vang7

Tải Outlook for iOS<https://aka.ms/o0ukef>
________________________________
Từ: Sotunde Sowoolu ***@***.***>
Đã gửi: Sunday, April 16, 2023 12:04:39 AM
Đến: ohmplatform/FreedomGPT ***@***.***>
Cc: Subscribed ***@***.***>
Chủ đề: Re: [ohmplatform/FreedomGPT] Errors after starting the windows app (Issue #16)


@Konzol<https://github.com/Konzol>
Had this same issue until I realized it was because I was missing the prod flag with the 'yarn start' command
Instead of 'yarn start:prod' i used just 'yarn start'

**Comment by Konzol** [comment]
Still not work, i got this error in cmd: `[7852:0422/113628.796:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is`
